/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectFrame;

import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ARNAB
 */
public class LoginUser extends javax.swing.JFrame {

    public static int a = 0;
    public static String s = "email";

    /**
     * Creates new form LoginUser
     */
    public LoginUser() {
        super("Institute of Information Technology, Alumni Association ");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailicon = new javax.swing.JLabel();
        passicon = new javax.swing.JLabel();
        emailtext = new javax.swing.JLabel();
        passtext = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        Passwordd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 786));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/email.png"))); // NOI18N
        getContentPane().add(emailicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        passicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/password.png"))); // NOI18N
        getContentPane().add(passicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        emailtext.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        emailtext.setText("Email        : ");
        getContentPane().add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 140, -1));

        passtext.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        passtext.setText("Password  :");
        getContentPane().add(passtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 140, -1));

        email.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 300, 50));
        email.getAccessibleContext().setAccessibleName("");

        btnlogin.setBackground(new java.awt.Color(255, 255, 255));
        btnlogin.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/user login.png"))); // NOI18N
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 150, 60));

        Passwordd.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Passwordd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassworddActionPerformed(evt);
            }
        });
        getContentPane().add(Passwordd, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 300, 50));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MEMBER LOGIN");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 260, 70));

        backbutton.setBackground(new java.awt.Color(204, 204, 255));
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/backbutton.png"))); // NOI18N
        backbutton.setBorder(null);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/background.jpg"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(1366, 786));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        int f1 = 0, f2 = 0;
        try {
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/db", "root", "BokhtiarS250@");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from project where Email = '" + email.getText() + "'");
            ResultSet rs1 = null;
            String mat = Passwordd.getText();
            if (rs.next() == true) {
                f1 = 1;
                a = 1;
                s = email.getText();
                String pass = rs.getString("Password");
                if (pass.equals(mat)) {
                    this.setVisible(false);
                    UserDashboard sd = new UserDashboard();
                    sd.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Email or Password is incorrect", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            rs1 = st.executeQuery("select * from tst where Email = '" + email.getText() + "'");
            if (rs1.next() == true) {
                f2 = 1;
                a = 2;
                s = email.getText();
                String pass1 = rs1.getString("Password");
                if (pass1.equals(mat)) {
                    this.setVisible(false);
                    UserDashboard sd = new UserDashboard();
                    sd.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Email or Password is incorrect", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            if (f1 == 0 && f2 == 0) {
                JOptionPane.showMessageDialog(this, "Please Register at first, you are not the member of this alumni.", "Error", JOptionPane.ERROR_MESSAGE);

            }

        } catch (HeadlessException | SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void PassworddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassworddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassworddActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        loginpage u = new loginpage();
        this.setVisible(false);
        u.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Passwordd;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnlogin;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailicon;
    private javax.swing.JLabel emailtext;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel passicon;
    private javax.swing.JLabel passtext;
    // End of variables declaration//GEN-END:variables
}
