/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectFrame;

import javax.swing.*;

/**
 *
 * @author Shawon
 */
public class ProjectFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form ProjectFrame1
     */
    public ProjectFrame1() {
        super("Institute of Information Technology, Alumni Association ");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        about = new javax.swing.JButton();
        contact = new javax.swing.JButton();
        reglog = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        achiv = new javax.swing.JButton();
        noticeboard = new javax.swing.JButton();
        gallery = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        about.setBackground(new java.awt.Color(255, 255, 255));
        about.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        about.setForeground(new java.awt.Color(0, 102, 102));
        about.setText("ABOUT US");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        getContentPane().add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 180, 40));

        contact.setBackground(new java.awt.Color(255, 255, 255));
        contact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contact.setForeground(new java.awt.Color(0, 102, 102));
        contact.setText("CONTACT US");
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 260, 180, 40));

        reglog.setBackground(new java.awt.Color(255, 255, 255));
        reglog.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reglog.setForeground(new java.awt.Color(0, 102, 102));
        reglog.setText("REGISTER/LOGIN");
        reglog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reglogActionPerformed(evt);
            }
        });
        getContentPane().add(reglog, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, 40));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 102, 102));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 640, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/iitalumni.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/rsz_1reg.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/galarry.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 350, 60, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/achv.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 60, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/rsz_exit.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 560, 60, 60));

        achiv.setBackground(new java.awt.Color(255, 255, 255));
        achiv.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        achiv.setForeground(new java.awt.Color(0, 102, 102));
        achiv.setText("ACHIVMENTS");
        achiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                achivActionPerformed(evt);
            }
        });
        getContentPane().add(achiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 180, 40));

        noticeboard.setBackground(new java.awt.Color(255, 255, 255));
        noticeboard.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        noticeboard.setForeground(new java.awt.Color(0, 102, 102));
        noticeboard.setText("NOTICE BOARD");
        noticeboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticeboardActionPerformed(evt);
            }
        });
        getContentPane().add(noticeboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 180, 40));

        gallery.setBackground(new java.awt.Color(255, 255, 255));
        gallery.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gallery.setForeground(new java.awt.Color(0, 102, 102));
        gallery.setText("PHOTO GALLERY");
        gallery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galleryActionPerformed(evt);
            }
        });
        getContentPane().add(gallery, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 430, 180, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/rsz_about_us.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 60, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/news.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 60, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/rsz_contact (1).png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 60, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/rsz_16246698e8fde0d4e5ada7eb9d2bd1071.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
         this.setVisible(false);
        aboutus sd=new aboutus();
        sd.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        this.setVisible(false);
        contactus sd=new contactus();
        sd.setVisible(true);
    }//GEN-LAST:event_contactActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JFrame frame = new JFrame("EXIT");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want Exit", "EXIT", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void reglogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reglogActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        loginpage sd=new loginpage();
        sd.setVisible(true);
    }//GEN-LAST:event_reglogActionPerformed

    private void achivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_achivActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Achivments sd=new Achivments();
        sd.setVisible(true);
    }//GEN-LAST:event_achivActionPerformed

    private void noticeboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticeboardActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Notice a= new Notice();
        a.setVisible(true);
    }//GEN-LAST:event_noticeboardActionPerformed

    private void galleryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galleryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PhotoGallery a= new PhotoGallery();
        a.setVisible(true);
    }//GEN-LAST:event_galleryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JButton achiv;
    private javax.swing.JButton contact;
    private javax.swing.JButton exit;
    private javax.swing.JButton gallery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton noticeboard;
    private javax.swing.JButton reglog;
    // End of variables declaration//GEN-END:variables
}
