/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectFrame;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARNAB
 */
public class SearchStudent extends javax.swing.JFrame {

    /**
     * Creates new form SearchStudent
     */
    String radio;
    public SearchStudent() {
        super("Institute of Information Technology, Alumni Association ");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JRadioButton();
        batch = new javax.swing.JRadioButton();
        skills = new javax.swing.JRadioButton();
        cwp = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        skey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        title.setText("SEARCH  ANY STUDENT ");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("SEARCH BY :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        buttonGroup1.add(fname);
        fname.setText("FIRST NAME");
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 120, -1));

        buttonGroup1.add(batch);
        batch.setText("BATCH");
        batch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchActionPerformed(evt);
            }
        });
        getContentPane().add(batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 140, -1));

        buttonGroup1.add(skills);
        skills.setText("SKILLS");
        skills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skillsActionPerformed(evt);
            }
        });
        getContentPane().add(skills, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 140, -1));

        buttonGroup1.add(cwp);
        cwp.setText("CURRENT WORKING PLACE");
        cwp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwpActionPerformed(evt);
            }
        });
        getContentPane().add(cwp, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("SEARCH KEY: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, -1));

        skey.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        skey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skeyActionPerformed(evt);
            }
        });
        getContentPane().add(skey, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 300, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("SEARCH RESULTS :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jScrollPane1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "First Name", "Last Name", "Phone No", "Address", "Batch", "Roll", "Hall", "Date of Birth", "Current Working Place", "Gender", "Religion", "Blood Group", "Skills"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 1350, 420));

        search.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        clear.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, -1, -1));

        backbutton.setBackground(new java.awt.Color(204, 204, 255));
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/backbutton.png"))); // NOI18N
        backbutton.setBorder(null);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 60));

        background.setForeground(new java.awt.Color(204, 255, 204));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectFrame/background.jpg"))); // NOI18N
        background.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void skillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skillsActionPerformed
        // TODO add your handling code here:
        if(skills.isSelected())
        {
            radio="Skills";
        }
    }//GEN-LAST:event_skillsActionPerformed

    private void skeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skeyActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{  
            Connection con = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/db", "root", "BokhtiarS250@");
            Statement st=con.createStatement();
             ResultSet rs;
           if(fname.isSelected())
        {
            radio="`First Name`";
        }
           if(batch.isSelected())
        {
            radio="`Batch`";
        }
           if(cwp.isSelected())
        {
            radio="`Current Working Place`";
        }
            if(skills.isSelected())
        {
            radio="`Skills`";
        }
            rs=st.executeQuery("SELECT `Email`,`First Name`, `Last Name`, `Phone No`, `Address`, `Batch`, `Roll`, `Hall`, `Date of Birth`, `Current Working Place`, `Gender`, `Religion`, `Blood Group`, `Skills` FROM `project` WHERE"+radio+ "LIKE" +"'%"+skey.getText()+"%'");
                    DefaultTableModel tb=(DefaultTableModel)jTable1.getModel();
           while(rs.next())
            {    String email=rs.getString("Email");
                 String Fname=rs.getString("First Name");
                 String Lname=rs.getString("Last Name");
                 String Phone=rs.getString("Phone No");
                 String Address=rs.getString("Address");
                 String Batch=rs.getString("Batch");
                 String Roll=rs.getString("Roll");
                 String Hall=rs.getString("Hall");
                 String Dob=rs.getString("Date of Birth");
                 String Cwp=rs.getString("Current Working Place");
                 String Gender=rs.getString("Gender");
                 String Religion=rs.getString("Religion");
                 String Blood=rs.getString("Blood Group");
                 String Skills=rs.getString("Skills");      
                Object[] data={email,Fname,Lname,Phone,Address,Batch,Roll,Hall,Dob,Cwp,Gender,Religion,Blood,Skills};
                
                  tb.addRow(data);
                
            }
          
           skey.setText("");
           
            con.close();
             
        } catch (SQLException ex) {
            Logger.getLogger(SearchStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_searchActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fnameActionPerformed

    private void batchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchActionPerformed
        // TODO add your handling code here:
        if(batch.isSelected())
        {
            radio="Batch";
        }
    }//GEN-LAST:event_batchActionPerformed

    private void cwpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwpActionPerformed
        // TODO add your handling code here:
        if(cwp.isSelected())
        {
            radio="`Current Working Place`";
        }
    }//GEN-LAST:event_cwpActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tb=(DefaultTableModel)jTable1.getModel();
         tb.getDataVector().removeAllElements();
           tb.fireTableDataChanged();
    }//GEN-LAST:event_clearActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        UserDashboard u=new UserDashboard();
        this.setVisible(false);
        u.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel background;
    private javax.swing.JRadioButton batch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton cwp;
    private javax.swing.JRadioButton fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search;
    private javax.swing.JTextField skey;
    private javax.swing.JRadioButton skills;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
